### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by msglueck**
privileges comment was wrong. READ/WRITE produced ```Internal error occurred: pq: permission denied to set role```

### CODE REVIEW

**Comment by arnarg** [comment]
The check for privileges is actually a simple [switch statement](https://github.com/movetokube/postgres-operator/blob/master/pkg/controller/postgresuser/postgresuser_controller.go#L172-L179). The error you are running into is somewhere else. The reason this works with `READER/WRITER` is because it falls in the default case and is actually making it an `OWNER`.

The error you are getting with `READ` and `WRITE` is because of something else. Are you using AWS RDS by any chance and not setting `POSTGRES_CLOUD_PROVIDER` env variable to `AWS`?

**Comment by msglueck** [comment]
🤦🏻‍♂️ sorry, got stood-up apparently. Stayed too long in office. I’m actually using Azure and the POSTGRES_CLOUD_PROVIDER env is set to AZURE. But will double check tomorrow and look deeper into the error I’m getting. Thanks !

**Comment by arnarg** [comment]
Actually the capitalization matters with the cloud provider and in azure's case it should be `Azure` and exactly like that. This should be fixed and the string ran through `ToLower` or `ToUpper` before we check it.

I'll close this pull request.

**Comment by arnarg** [comment]
But please open an issue if that doesn't fix your problem.

**Pull request closed without merging**
