### PR TITLE
operator-sdk update from v0.17.1 to v0.18.0

### PR DESCRIPTION
**Pull request by hitman99**
Needs e2e testing as it might break things

### CODE REVIEW

**Comment by reddec** [comment]
Hi! @hitman99 any updates on this? Seems like it should solve problem with CRD

**Comment by hitman99** [comment]
I have some time allocated next week to work on this project and will do a new release of the operator with these changes.

**Comment by reddec** [comment]
Thanks!

**Comment by hitman99** [comment]
Hey @arnarg, does this look ok? There's a lot of changes, but all were done by operator-sdk upgrade docs. The major difference is `apiextensions.k8s.io/v1beta1` upgrade to `apiextensions.k8s.io/v1`. Starting from kubernetes v1.22 the v1beta1 is deprecated and no longer served. I've tested the v1 CRDs and it works well.

**Review by arnarg — APPROVED** [review]
LGTM

**Comment by endersonmaia** [comment]
this PR should close #73

**Comment by tuler** [comment]
Any expectation of merging this?
Thanks

**Pull request merged**
