### PR TITLE
Adding masterRole option to Postgres CRD

### LINKED ISSUE #11: There should be an option in Postgres CRD that uses an existing owner role of a database
This could be a variable `spec.masterRole` in the `Postgres` CRD of type string.

When set it should skip creating a group role owner of the database and instead use the existing one.

### PR DESCRIPTION
**Pull request by arnarg**
Fixes #11

### CODE REVIEW

**Comment by arnarg** [comment]
@hitman99 I use [operator-sdk](https://github.com/operator-framework/operator-sdk) to generate the CRDs and other code generation (using `operator-sdk generate openapi` and `operator-sdk generate k8s`). The newer version I'm using now wants to create `db.movetokube.com_postgres_crd.yaml` instead of the previous `db_v1alpha1_postgres_crd.yaml`.

Should I delete the old ones? What do you use for code generation?

**Comment by hitman99** [comment]
@arnarg I use the same thing, but don't remember which version I used to boostrap this project. There might be an issue because of the operator-sdk versioning. Which version are you using?
In addition, I've opened a new issue to refactor the dependency management to go modules instead of dep, which I'll take care when time permits.

**Comment by arnarg** [comment]
> I use the same thing, but don't remember which version I used to boostrap this project. There might be an issue because of the operator-sdk versioning. Which version are you using?

I updated recently and I have `v0.11.0`.
We should be running the code generation every time we change something in `postgres_types.go` and `postgresuser_types.go` as far as I'm aware.

> In addition, I've opened a new issue to refactor the dependency management to go modules instead of dep, which I'll take care when time permits.

I like that ;)

**Comment by hitman99** [comment]
@arnarg Sorry to bring this up again, but it seems that we now have duplicate CRDs for `Postgres` and `PostgresUser`. Should we delete the old and keep the new?

**Comment by arnarg** [comment]
@hitman99 I think that should be done, yes. It seems the operator-sdk has changed it so this will happen again.

**Comment by hitman99** [comment]
Ok, let's handle this in a separate PR

**Pull request merged**
