### PR TITLE
Switch Kustomization Image to GHCR Repository

### PR DESCRIPTION
**Pull request by apeschel**
Fixes: https://github.com/movetokube/postgres-operator/issues/113

### CODE REVIEW

**Comment by ElementSpanky** [comment]
@hitman99 Thanks for releasing 1.2.3! Unfortunately, this needs to be fixed so we can pick up the changes.

Any chance you can roll this out, too?

**Comment by apeschel** [comment]
The deployment in the kustomization doesn't have a version set - so this will still only partly fix the version problem for the kustomization.

**Comment by apeschel** [comment]
@hitman99 I'm not sure how you want to try to keep the kustomization in sync with the releases. If you have a suggestion, I can try to patch it for you.

**Comment by hitman99** [comment]
Actually, with the last release I re-introduced pushes to dockerhub again so the deployment should work now. Both GHCR and dockerhub have latest tag pointing to the latest version (1.2.3) now

**Pull request closed without merging**
