### PR TITLE
Updating dependencies to operator-sdk 0.14.0

### PR DESCRIPTION
**Pull request by arnarg**
This is in preparation for fixing #35 

Patch is not available on controller-runtime's client in older versions.

I created a new dummy project with operator-sdk 0.14.0 and transferred over the versions in `go.mod`. There was also some changes in the main method that I copied from the newer version project.

### CODE REVIEW

**Comment by hitman99** [comment]
There seems to be an issue while trying to build it. Does it build for you?
```
# github.com/movetokube/postgres-operator/pkg/controller/postgres
pkg/controller/postgres/postgres_controller.go:278:39: cannot use &client.ListOptions literal (type *client.ListOptions) as type runtime.Object in argument to r.client.List:
	*client.ListOptions does not implement runtime.Object (missing DeepCopyObject method)
pkg/controller/postgres/postgres_controller.go:278:62: cannot use &dbs (type *v1alpha1.PostgresList) as type client.ListOption in argument to r.client.List:
	*v1alpha1.PostgresList does not implement client.ListOption (missing ApplyToList method)
```

**Comment by hitman99** [comment]
I've added automated build and checks in order not to merge code that does not build. Later we could add tests to that policy too

**Comment by arnarg** [comment]
> There seems to be an issue while trying to build it. Does it build for you?

Oh shit, I fixed that but forgot to check it in. I'll add them when I get to a computer.

**Comment by hitman99** [comment]
> Oh shit

No worries man 😄

**Comment by arnarg** [comment]
I pulled in your automated build from master and fixed the compile error

**Pull request merged**
